## targets

## USB support ##

e:
	@$(MAKE) bin MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) USB="USB" B=E NTFS=y EBTABLES=y IPV6SUPP=y USBEXTRAS=y BCMNAT=y OPENVPN=y PPTPD=y \
	    BBEXTRAS=y STUBBY=y ADVTHEMES=y OPENSSL11=y PROXY=y BUILD_DESC="$(VPN)"

c:
	@$(MAKE) bin MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) USB="USB" B=M NTFS=y EBTABLES=y IPV6SUPP=y USBEXTRAS=y BCMNAT=y OPENVPN=y PPTPD=y \
	    BBEXTRAS=y BTGUI=y STUBBY=y ADVTHEMES=y OPENSSL11=y PROXY=y BUILD_DESC="BTgui-VPN"

d:
	@$(MAKE) bin MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) USB="USB" B=M NTFS=y EBTABLES=y IPV6SUPP=y USBEXTRAS=y BCMNAT=y OPENVPN=y PPTPD=y \
	    BBEXTRAS=y BTGUI=y STUBBY=y NOCAT=y ADVTHEMES=y OPENSSL11=y PROXY=y BUILD_DESC="Nocat-VPN"

u:
	@$(MAKE) bin MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) USB="USB" B=M NTFS=y EBTABLES=y IPV6SUPP=y USBEXTRAS=y BCMNAT=y \
	    BTCLIENT=y ADVTHEMES=y OPENSSL11=y PROXY=y BUILD_DESC="BT"

t:
	@$(MAKE) bin MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) USB="USB" B=M NTFS=y EBTABLES=y IPV6SUPP=y USBEXTRAS=y BCMNAT=y OPENVPN=y PPTPD=y \
	    NO_JFFS=y BTCLIENT=y ADVTHEMES=y OPENSSL11=y PROXY=y BUILD_DESC="BT-VPN"

b:
	@$(MAKE) bin MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) USB="USB" B=M NTFS=y EBTABLES=y IPV6SUPP=y USBEXTRAS=y BCMNAT=y OPENVPN=y PPTPD=y \
	    BBEXTRAS=y BTGUI=y STUBBY=y NO_CIFS=y NO_JFFS=y NFS=y ADVTHEMES=y OPENSSL11=y PROXY=y BUILD_DESC="Big-VPN"

o:
	@$(MAKE) bin MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) USB="USB" B=E NTFS=y EBTABLES=y IPV6SUPP=y USBEXTRAS=y BCMNAT=y OPENVPN=y KEYGEN=y PPTPD=y \
	    BBEXTRAS=y MEDIASRV=y DNSCRYPT=y STUBBY=y NOCAT=y TOR=y BTCLIENT=y NFS=y SNMP=y UPS=y TR_EXTRAS=y IPSEC=y DNSSEC=y TINC=y NANO=y HFS=y IPERF=y TERMLIB=y ADVTHEMES=y OPENSSL11=y PROXY=y BONDING=y FULL_EXTRAS=y BUILD_DESC="Mega-VPN"

z:
	@$(MAKE) bin MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) USB="USB" B=E NTFS=y EBTABLES=y IPV6SUPP=y USBEXTRAS=y BCMNAT=y OPENVPN=y KEYGEN=y PPTPD=y \
	    BBEXTRAS=y MEDIASRV=y DNSCRYPT=y STUBBY=y NOCAT=y TOR=y BTCLIENT=y NFS=y SNMP=y UPS=y TR_EXTRAS=y IPSEC=y DNSSEC=y TINC=y NANO=y HFS=y NGINX=y IPERF=y TERMLIB=y ADVTHEMES=y OPENSSL30=y PROXY=y BONDING=y MDNS=y QRCODE=y AIO=y FULL_EXTRAS=y BUILD_DESC="AIO"


## NO USB support ##

f:
	@$(MAKE) bin MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) USB="" B=F NO_CIFS=y JFFSv1=y NO_ZEBRA=y BCMNAT=y PROXY=y BUILD_DESC="Mini"

i:
	@$(MAKE) bin MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) USB="" B=I NO_CIFS=y NO_ZEBRA=y NO_JFFS=y IPV6SUPP=y NO_HTTPS=y BCMNAT=y PROXY=y BUILD_DESC="MiniIPv6"

j:
	@$(MAKE) bin MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) USB="" B=V NO_CIFS=y NO_ZEBRA=y NO_JFFS=y OPENVPN=y NO_ADBLOCK=y NO_DMZ=y NO_L7=y OPTIMIZE_SIZE_MORE=y KERN_SIZE_OPT_MORE=y BUILD_DESC="MiniVPN"

j2:
	@$(MAKE) bin MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) USB="" B=V NO_CIFS=y NO_ZEBRA=y NO_JFFS=y PPTPD=y NO_ADBLOCK=y OPTIMIZE_SIZE_MORE=y KERN_SIZE_OPT_MORE=y PROXY=y BUILD_DESC="MiniVPN2"

v:
	@$(MAKE) bin MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) USB="" B=V NO_JFFS=y IPV6SUPP=y OPENVPN=y PPTPD=y NO_ADBLOCK=y OPTIMIZE_SIZE_MORE=y KERN_SIZE_OPT_MORE=y PROXY=y BUILD_DESC="IPv6-$(VPN)"

m:
	@$(MAKE) bin MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) USB="" B=E IPV6SUPP=y OPENVPN=y KEYGEN=y PPTPD=y NOCAT=y NFS=y SNMP=y STUBBY=y TOR=y BBEXTRAS=y EBTABLES=y BCMNAT=y ADVTHEMES=y OPENSSL11=y PROXY=y BUILD_DESC="Max"


## MIPS32R2 ##
r2z:
	@$(MAKE) z MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=32

r2e:
	@$(MAKE) e MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=32

r2c:
	@$(MAKE) c MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=32

r2u:
	@$(MAKE) u MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=32

r2t:
	@$(MAKE) t MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=32

r2d:
	@$(MAKE) d MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=32

r2b:
	@$(MAKE) b MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=32

r2o:
	@$(MAKE) o MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=32

r2f:
	@$(MAKE) f MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 BELKIN=y NVRAM_SIZE=32

r2i:
	@$(MAKE) i MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=32

r2j:
	@$(MAKE) j MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=32

r2j2:
	@$(MAKE) j2 MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=32

r2v:
	@$(MAKE) v MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=32

r2m:
	@$(MAKE) m MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=32


## Linksys E-series witk 60K NVRAM ##
n60e:
	@$(MAKE) e MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=60 LINKSYS_E=y

n60c:
	@$(MAKE) c MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=60 LINKSYS_E=y

n60u:
	@$(MAKE) u MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=60 LINKSYS_E=y

n60t:
	@$(MAKE) t MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=60 LINKSYS_E=y

n60b:
	@$(MAKE) b MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=60 LINKSYS_E=y

n60d:
	@$(MAKE) d MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=60 LINKSYS_E=y

n60o:
	@$(MAKE) o MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=60 LINKSYS_E=y

n60v:
	@$(MAKE) v MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=60 LINKSYS_E=y

n60m:
	@$(MAKE) m MWAN_MAX=$(if $(MWAN_MAX),$(MWAN_MAX),4) MIPS32=r2 NVRAM_SIZE=60 LINKSYS_E=y
